# Prints accumulated Caffe2 configuration summary
function(print_configuration_summary)
    message(STATUS "")
    message(STATUS "Configuration script parsing status [")
    message(STATUS "  Description             : ${CMAKE_PROJECT_NAME}")
    message(STATUS "  Version                 : ${PROJECT_VERSION} (${GIT_SHORT_HASH})")
    message(STATUS "  Build type              : ${CMAKE_BUILD_TYPE}")
    if(BUILD_SHARED_LIBS)
    message(STATUS "  Librarian mode          : SHARED")
    else()
    message(STATUS "  Librarian mode          : STATIC")
    endif()
    message(STATUS "  Source directory        : ${CMAKE_SOURCE_DIR}")
    message(STATUS "  Build directory         : ${CMAKE_BINARY_DIR}")
    message(STATUS "]")
    message(STATUS "")
endfunction()